
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-CourseEndBug","number":69,"title":"BUG fixed: Course can end before it starts","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/69"},{"author":{"id":"U_kgDOCL9k9A","is_bot":false,"login":"djoyneruscb","name":"David"},"headRefName":"DJ-IncorrectLoginTime","number":67,"title":"DJ-Issue #7, Last Online in User Profile Defaults to Wrong Date Fix","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/67"},{"author":{"id":"U_kgDOBtxmKA","is_bot":false,"login":"Aavash-Adhikari","name":""},"headRefName":"AA-BUG-3","number":64,"title":"fixed footer typo","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/64"}]
