
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBaDySw","is_bot":false,"login":"AdmPenguin","name":"Bao T."},"headRefName":"bt-ep1f5","number":83,"title":"BT: EPIC Frontend - Course Term Regex and Error","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/83"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-confirmToggles","number":82,"title":"Feature: Confirm when toggling admin or instructor priveleges","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/82"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-popUpAdminToggle","number":81,"title":"BUG Fixed: Admin toggling his own privileges off","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/81"},{"author":{"id":"U_kgDOBaDySw","is_bot":false,"login":"AdmPenguin","name":"Bao T."},"headRefName":"bt-ep1f4","number":80,"title":"BT: EPIC Frontend - Term Descriptions","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/80"},{"author":{"id":"U_kgDOBtxmKA","is_bot":false,"login":"Aavash-Adhikari","name":""},"headRefName":"BUG-5-ICON","number":79,"title":"Bug 5 icon","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/79"},{"author":{"id":"U_kgDOBaDySw","is_bot":false,"login":"AdmPenguin","name":"Bao T."},"headRefName":"bt-ep1f3","number":78,"title":"BT: EPIC Frontend - School Dropdown","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/78"},{"author":{"id":"U_kgDOCL9k9A","is_bot":false,"login":"djoyneruscb","name":"David"},"headRefName":"DJ-NormalUserCanSeeCourses","number":76,"title":"DJ-normal user can see courses","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/76"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-EP2-F5","number":75,"title":"LZ - Complete EPIC 2 F5 and Fix Storybook Entries of Course Table and Pages","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/75"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-EP2-F4","number":74,"title":"LZ - Complete EPIC 2 F4","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/74"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-CourseEndBug","number":69,"title":"BUG fixed: Course can end before it starts","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/pull/69"}]
